name: Python Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ env.COMMIT_SHA }}
          docker build -t $IMAGE_TAG .
          echo "Docker image built with tag $IMAGE_TAG"

      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ env.COMMIT_SHA }}
          docker push $IMAGE_TAG
          echo "Docker image pushed to Docker Hub successfully with tag $IMAGE_TAG"

  update-config:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: oaleev/mann-gitops-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mann-gitops-config
          ref: main

      - name: Update image in deployment manifest
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ env.COMMIT_SHA }}
          sed -i "s|image: .*|image: $IMAGE_TAG|g" mann-gitops-config/manifests/deployment.yaml
          cd mann-gitops-config
          git config --global user.email "mina@naveenmannam.com"
          git config --global user.name "oaleev"
          git add .
          git commit -m "Update image to $IMAGE_TAG"
          git push origin main
